GET http://localhost:3000/api/sauces

Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbl9oaWxsXzc4NUBob3RtYWlsLmZyIiwiaWF0IjoxNjc4OTM1NTk3LCJleHAiOjE2NzkwMjE5OTd9.lmpm-L9JJMJ5RiZ3ywrSCMM84jVJIvURRVShTzF70rY
 

